### ISSUE TITLE
Web

### ISSUE THREAD

**Issue by vegroland** [icebob/hasznaltauto-figyelo#1]
Szia,
feltettem gépre és tökéletesen működik. Viszont webes platformon lenne rá igazán szükség.
Próbáltam node.js hoston, de ott ugyanaz a beállítás lefut ugyan, de eredmény nélkül. (evennode.com)
Mi lehet a probléma, amiatt nem kap eredményt? Error_logban nincs semmi.
Előre is köszönöm!

**Comment by icebob** [comment]
Szia,

úgy néz ki [néhány országból](https://geopeeker.com/fetch/?url=http%3A%2F%2Fwww.hasznaltauto.hu%2Ftalalatilista%2Fauto%2F2G4ZLM6H4LHPDGMCKJQHZDH4T2PHATRPML46HMGZD5WYO4RCKTY1QY69R2S5GSOSA2LWHHFZA4RAMCAMTTFT3HQUMW3F0OZ9RMYDQRLYCCLDQW734RMFTH7Z2GZY31W1Y5WO6UISWJC1H9SOJT9Y8PY4YPLDTJ6905AHHT11QIF2HML0FAC2CIC9YEMGCW0W2EGOKOE9TEP0M1Q8PUF4C7FEJU22745MKGG2TY2F3F7HI5LR2EOTHH9UR2OQ499J2FM0DFAWMK9DQKHE3HZL7TG7LRAS8U1UE4II1IA5KLPZO0K6C1TS7G3ZUFOIUQK26WH61FY0Z7YT6JZRRIYE99KLOGY20WF3JJY6Y2KQAHKEJR6ZRUH970AUOMD%2Fpage1) nem érhető el az oldal. Szerintem ez lehet az oka, hogy nem működik.

**Comment by vegroland** [comment]
Köszönöm az infót. Bár európai szerverről ment, lehet, hogy ez volt a hiba.
Azóta csak gépen fut, viszont előjött egy hiba. Kb. 2-3 napig tökéletesen működött. Hétvégén nem futott, majd újra használva gyakorlatilag folyamatosan küldi ki, hogy új autót talált. (persze ugyanazokat).
(feltettem másik gépre, ott is ugyanez történik)
Mi lehet a  megoldás?

**Comment by icebob** [comment]
Hibát nem ír a konzolra? Esetleg küld el a keresési linket amit ismétel és kipróbálom.

Esetleg hotfix-ként próbáld meg hogy leállítod, letörlöd a data mappát és elindítod. Elsőre ki fog hozni mindent, de hátha utána már jó lesz.

**Comment by vegroland** [comment]
A probléma megoldódott a data mappa törlésével!
(egyébként mindegy volt, hogy új linkeket veszek-e fel, megváltoztatom az ID-t vagy a nevet, miközben a konzolon semmi hibaüzenet nem volt)
Köszi szépen még egyszer a segítséget!!

**Comment by icebob** [comment]
Nincsmit!
