### ISSUE TITLE
Nincs találat

### ISSUE THREAD

**Issue by vegroland** [icebob/hasznaltauto-figyelo#6]
Szia,

4 év után újra szeretném használni a keresőt.
Feltelepítettem különböző gépekre is, mert folyamatosan hibát kaptam.
Aztán végre működni látszik, de mindenre 0 találatot ad, ami valójában nem valós eredmény.

Életre keltettem egy akkori (2017-es) gépet is amin futott és pont ugyanaz a "hiba', azaz egy darab találat sincs.
Az egyetlen amit észreveszek, hogy a link struktúrája megváltozott a hasznaltauto.hu-n. Lehet ez a probléma? (nincs már "/auto/" illetve a végén a "/page1")

Előre is köszönöm az újbóli segítséget!

Üdv,
Roland

**Comment by icebob** [comment]
Mi a pontos hiba? Én most ráindítottam és legyűjtötte az adatokat.
![image](https://user-images.githubusercontent.com/306521/146054982-0a43e5f6-a030-41bb-821f-d844d665fd7e.png)

**Comment by vegroland** [comment]
Minden keresésre az alábbit adja.
Pl. ezt a keresési linket használva, amire az összes találatot dobnia kellene: shorturl.at/fmBPW (a shorturl-t csak itt használom, a programban a rendes van)
![image](https://user-images.githubusercontent.com/29103072/146059352-c3ae83ba-64f5-4577-9a39-8c1600414429.png)

De semmilyen formában nem tudom eredményre bírni. A régi gépen, amin működött, szintén ez a gond most, hogy újraindítottam.

**Comment by vegroland** [comment]
Ez a helyzet az alap, általad megadott 2 keresési linkkel is.
Őszintén szólva foglalmam sincs, hogy mi lehet a gond, ha Nálad pedig működik.
(Ahogy látod Win-en használom, de ez eddig nem jelentett gondot; gondolom most sem az)

![image](https://user-images.githubusercontent.com/29103072/146154825-5c2bc999-db69-4446-b97e-2ae934b937ee.png)

**Comment by vegroland** [comment]
Szia,

van esetleg bármilyen ötleded, javaslatod? Esetleg az , hogy Windowson fut?

**Comment by icebob** [comment]
Csatold be a `config.js`-edet hátha azzal elő tudom idézni.

**Comment by vegroland** [comment]
> Csatold be a `config.js`-edet hátha azzal elő tudom idézni.

icebob: töröltem innen a linket, mert a fájlban érzékeny adat is volt.

**Comment by icebob** [comment]
Kipróbáltam belőle az elsőt a `toyota_corolla_newsearch`-t és működött. Ami feltűnt, hogy nekem megvan adva a `mailgunDomain` is az `email` alatt a config.json-ben. Bár ez már csak akkor okozhat gondot, ha van is találata.

**Comment by vegroland** [comment]
Egyrészt köszönöm, hogy törölted a linket és hogy időt szántál rá, hogy megnézd!
Az első keresés még a 4 évvel ezelőtti működőből volt benne, az utána lévők az újak, bár valójában nem számít, mert valamiért mindegyiknél 0 az első találat és nem is jár sikerrel egyszer sem.
Nem igazán értem, hogy mi lehet a probléma, főleg hogy Nálad van találat.

`mailgunDomain` nem volt egyébként a fájlban, csak a `mailgunKey`. (nem töröltem belőle semmit)
Próbáltad egyébként a teljeset lefuttatni?
Bár ezelőtt működött Windowson, ha megoldásnak gondolod, előfizetnék egy linux vps-re, hogy ott futtassam.

**Comment by icebob** [comment]
Esetleg próbáltad a data mappát törölni és úgy futtatni? Ott tárolja a korábbi találatokat, szal ha az üres, akkor mindenképp mindenről kellene küldenie.

**Comment by icebob** [comment]
Btw, én Node v12.22-ön futtatom. Ha nálad újabb vagy régebbi van, akkor lehet ez a különbség.

De csináltam egy videót, hogy egy új mappába újra leszedem és elindítom a default config-al. A végén elpukkan, mert az email küldés nincs beállítva, de leszedte a találatokat.

https://user-images.githubusercontent.com/306521/147883787-2bb7be88-7a78-4739-9f32-f25cee2954e2.mp4

**Comment by vegroland** [comment]
Szia,

csak most volt időm foglalkozni vele.
Hálásan köszönöm a videót!!
Végigmentem a lépéseken és az npm-mel volt a gond, amit orvosoltam.

Most már szuperül megy; van találat és a mail is kimegy! :)

Ezer köszönet a segítségedért még egyszer!
