### ISSUE TITLE
Nem ír árakat

### ISSUE THREAD

**Issue by freeroam1234** [icebob/hasznaltauto-figyelo#8]
Nem küldi az árakat. Erre tud valaki valami megoldast?
![BE1CDC4D-E09A-4E0D-8E04-A2271EA4D2A6](https://user-images.githubusercontent.com/12865889/176183353-3dc302c0-4147-4e53-9b98-2bbaadd5e054.png)

**Comment by rahyabaron** [comment]
szia, látom neked nem ír árakat, de a mailgunos free domainról tud küldeni emaileket? nekem sajnos az se megy
[https://imgur.com/a/qliACb1](url)

**Comment by rahyabaron** [comment]
szia, látom neked nem ír árakat, de a mailgunos free domainról tud küldeni emaileket? nekem sajnos az se megy.
![hasznfigydomain](https://user-images.githubusercontent.com/108933520/177983396-91499524-f269-42ba-a8bf-4032c099885b.png)

**Comment by freeroam1234** [comment]
Szia! Nekem a mailgun kuldi a maileket. Nezd at a configod.

rahyabaron ***@***.***> (időpont: 2022. júl. 8., P, 13:24)
ezt írta:

**Comment by rahyabaron** [comment]
de akkor nem vagy előfizetve rá vagy ilyesmi ugye? free domaint használod?

**Comment by rahyabaron** [comment]
az egyik email cím amit megadtam nem volt whitelist-es mailgunon mostmár jó :D

**Comment by freeroam1234** [comment]
Szuper! Neked az arakat kiirja?

rahyabaron ***@***.***> (időpont: 2022. júl. 8., P, 13:42)
ezt írta:

**Comment by rahyabaron** [comment]
nem, azt nekem se írja

**Comment by rahyabaron** [comment]
Van megoldás erre is mostmár, gondolom változott mostanság az oldal:
az index.js-ben van egy ilyen sor hogy:    price: ".col-sm-9.hidden-xs .vetelar",
na most ezt a sort átírva erre:                   price: ".col-sm-8.hidden-xs .price-fields-desktop .pricefield-primary",
így kiírja az első árat amit megadnak.

**Comment by icebob** [comment]
Javítva.

**Comment by freeroam1234** [comment]
Esetleg egy olyan funkciót nem lehetne beletenni, hogy csak a
maganszemelyek altal felrakott autokat listazza? Kicsit idegesito, amikor a
kereskedok 2 naponta felrakjak ugyan azt…

Icebob ***@***.***> (időpont: 2022. júl. 8., P, 14:50) ezt
írta:

**Comment by davidszuhi** [comment]
B
